# Generated by Django 4.1.7 on 2023-03-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='condition',
        ),
        migrations.AddField(
            model_name='device',
            name='condition_when_assigned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='condition_when_returned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
