# Generated by Django 4.1.7 on 2023-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0002_remove_device_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='condition_when_assigned',
        ),
        migrations.RemoveField(
            model_name='device',
            name='condition_when_returned',
        ),
        migrations.AddField(
            model_name='device',
            name='condition',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='assigned_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='returned_date',
            field=models.DateTimeField(),
        ),
    ]
