# Generated by Django 4.1.7 on 2023-03-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0004_device_condition_when_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='condition',
        ),
    ]
